version: '3.8'

networks:
  router_network:
    driver: bridge

services:
  router_metrics:
    build: .
    environment:
      - ROUTER_URL=http://192.168.1.1  # Adjust this URL as needed
      - ROUTER_USERNAME=admin
      - ROUTER_PASSWORD=<pass>
    ports:
      - 8000:8000
    restart: unless-stopped
    networks:
      - router_network

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:z
    ports:
      - 9090:9090
    restart: unless-stopped
    networks:
      - router_network

  grafana:
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    restart: unless-stopped
    depends_on:
      - prometheus
    networks:
      - router_network
