global:
  scrape_interval: 1m  # Set the scrape interval to 1 minute

scrape_configs:
  - job_name: 'router_metrics'
    static_configs:
      - targets: ['router_metrics:8000']  # Target the router_metrics service
